_wandb:
    value:
        cli_version: 0.25.0
        e:
            d183mdowsuq8oscgqah4gzi62c0pehns:
                args:
                    - --env_name=LeapXELACubeRotateZAxis
                    - --impl
                    - warp
                    - --device
                    - cuda:0
                    - --use_wandb
                    - "True"
                codePath: train_rsl_rl.py
                codePathLocal: train_rsl_rl.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1966736678912"
                        used: "1459827159040"
                email: mohammad200h@hotmail.com
                executable: /usr/bin/python3
                git:
                    remote: git@github.com:mohammad200h/mujoco_playground.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-bf0b8999-a9f8-10ee-5cfe-831ec7f4c565
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-9e5e2fab-4ec0-68a7-c2f5-0ddaf9e6b93d
                host: mamaad
                memory:
                    total: "67249692672"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.35
                program: /workspace/mujoco_playground/learning/train_rsl_rl.py
                python: CPython 3.11.14
                root: /workspace/mujoco_playground/learning
                startedAt: "2026-03-10T17:54:14.313806Z"
                writerId: d183mdowsuq8oscgqah4gzi62c0pehns
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 12
                - 45
                - 105
            "2":
                - 1
                - 12
                - 45
                - 105
            "3":
                - 13
                - 34
                - 41
            "4": 3.11.14
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
action_repeat:
    value: 1
action_scale:
    value: 0.6
ctrl_dt:
    value: 0.05
early_termination:
    value: true
env_name:
    value: LeapXELACubeRotateZAxis
episode_length:
    value: 500
finger_tip_type:
    value: Box
history_len:
    value: 1
impl:
    value: warp
nconmax:
    value: 245760
njmax:
    value: 170
noise_config:
    value:
        level: 1
        scales:
            joint_pos: 0.05
reward_config:
    value:
        scales:
            action_rate: 0
            angvel: 1
            energy: 0
            linvel: 0
            pose: 0
            termination: -100
            torques: 0
sim_dt:
    value: 0.01
